COLNAMES_KEY = {
    "Goals": "goals",
    "Possession": "possession",
    "Shots / on target": ["shots", "shots_on_target"],
    "Number of possessions": "num_of_possessions",
    "Shots on post / blocked / wide": ["shots_on_post", "shots_blocked", "shots_wide"],
    "Possessions reaching opponent half": [
        "possessions_end_in_opp_half",
        "perc_total_possessions_end_in_opp_half",
    ],
    "From penalty area / on target": [
        "shots_inside_box",
        "shots_on_target_inside_box",
        "shots_on_target_inside_box_perc",
    ],
    "Possessions reaching opponent penalty area": [
        "posssessions_end_in_opp_box",
        "perc_total_possessions_end_in_opp_box",
    ],
    "Outside penalty area / on target": [
        "shots_outside_box",
        "shots_on_target_outside_box",
        "shots_on_target_outside_box_perc",
    ],
    "Average possession duration": "average_possession_time",
    "Corners": "corners",
    "Free kicks": "free_kicks",
    "Offsides": "offsides",
    "Total": "total_open_play_possessions",
    "Fouls / suffered": ["fouls_committed", "fouls_drawn"],
    "Short": "num_short_possessions",
    "Yellow / red cards": ["yellows", "reds"],
    "Medium": "num_medium_possessions",
    "Long": "num_long_possessions",
    "Very long": "num_very_long_possessions",
    "Total / with shots": [
        "total_attacks",
        "total_attacks_with_shots",
        "total_attacks_to_shot_rate",
    ],
    "Positional attacks / with shots": [
        "num_positional_attacks",
        "positional_attacks_with_shots",
        "positional_attacks_to_shot_rate",
    ],
    "Counterattacks": "counters",
    "Total passes / accurate": [
        "total_passes_attempted",
        "total_accurate_passes",
        "total_passing_accuracy",
    ],
    "Free kicks / with shots": [
        "total_free_kicks",
        "free_kicks_with_shots",
        "free_kick_shot_perc",
    ],
    "Forward passes / accurate": [
        "forward_passes_attempted",
        "forward_accurate_passes",
        "forward_passing_accuracy",
    ],
    "Corners / with shots": ["total_corners", "corners_with_shots", "corner_shot_perc"],
    "Back passes / accurate": [
        "back_passes_attempted",
        "back_accurate_passes",
        "back_passing_accuracy",
    ],
    "Lateral passes / accurate": [
        "lateral_passes_attempted",
        "lateral_accurate_passes",
        "lateral_passing_accuracy",
    ],
    "Progressive passes / accurate": [
        "progressive_passes_attempted",
        "progressive_accurate_passes",
        "progressive_passing_accuracy",
    ],
    "Sliding tackles": "slide_tackles",
    "Long passes / accurate": [
        "long_passes_attempted",
        "long_accurate_passes",
        "long_passing_accuracy",
    ],
    "Interceptions": "interceptions",
    "Passes to final third / accurate": [
        "fin_third_passes_attempted",
        "fin_third_accurate_passes",
        "fin_third_passing_accuracy",
    ],
    "Clearances": "clearances",
    "Average pass to final third length (m)": "average_pass_to_final_third_length",
    "Passes allowed per def . action (PPDA)": "ppda",
    "Passes to penalty area / accurate": [
        "passes_to_box_attempted",
        "accurate_passes_to_box",
        "passes_to_box_accuracy",
    ],
    "Shot assists": "shot_assists",
    "Recoveries / low / medium / high": [
        "total_recoveries",
        "recoveries_own_third",
        "recoveries_mid_third",
        "recoveries_opp_third",
    ],
    # "Smart passes / accurate": [
    #     "smart_passes_attempted",
    #     "accurate_smart_passes",
    #     "smart_passing_accuracy",
    # ],
    # "Through passes / accurate": [
    #     "through_balls_attempted",
    #     "accurate_through_balls",
    #     "through_ball_accuracy",
    # ],
    "Opponent half recoveries": "recoveries_in_opp_half",
    "Crosses / accurate": ["total_crosses", "accurate_crosses", "crossing_accuracy"],
    "Losses / low / medium / high": [
        "total_losses",
        "losses_own_third",
        "losses_mid_third",
        "losses_opp_third",
    ],
    "Crosses : low / high / blocked": [
        "low_crosses",
        "high_crosses",
        "blocked_crosses",
    ],
    "Deep completions": "deep_completions",
    "Total duels / won": ["total_duels", "total_duels_won", "total_duel_win_rate"],
    "Average pass length (m)": "average_pass_length",
    "Offensive duels / won": [
        "offensive_duels",
        "offensive_duels_won",
        "offensive_duels_win_rate",
    ],
    "Defensive duels / won": [
        "defensive_duels",
        "defensive_duels_won",
        "defensive_duels_win_rate",
    ],
    "Loose ball duels / won": [
        "loose_ball_duels",
        "loose_balls_won",
        "loose_ball_win_rate",
    ],
    "Aerial duels / won": ["aerial_duels", "aerial_duels_won", "aerial_duel_win_rate"],
    "Dribbles / successful": [
        "dribbles_attempted",
        "successful_dribbles",
        "dribbling_success_rate",
    ],
    "Challenge intensity": "challenge_intensity",
    "xG": "xG",
    "Pure possession time": "possession_time",
    "Average shot distance (m)": "average_shot_dist",
    "Match tempo": "match_tempo",
}

TEAM_ATTACKING_COLUMNS = [
    "match_date",
    "opponent_team_name",
    "shots",
    "shots_on_target",
    "posssessions_end_in_opp_box",
    "perc_total_possessions_end_in_opp_box",
    "prec_total_set_pieces_w_shots",
    "progressive_passes_attempted",
    "progressive_passing_accuracy",
    "total_crosses",
    "crossing_accuracy",
    "shot_assists",
    "losses_own_third",
    "losses_mid_third",
    "match_tempo",
]

TEAM_ATTACKING_RENAME = {
    "shots": "Shots Attempted",
    "shots_on_target": "Shots on Target",
    "posssessions_end_in_opp_box": "# of Possessions Ending in Opponent's Box",
    "perc_total_possessions_end_in_opp_box": "% Possessions Ending in Opponent's Box",
    "prec_total_set_pieces_w_shots": "% Set Pieces Ending in shot",
    "progressive_passes_attempted": "Progressive Passes Attempted",
    "progressive_passing_accuracy": "Progressive Passing Accuracy",
    "total_crosses": "Total Crosses Attempted",
    "crossing_accuracy": "Total Crossing Accuracy",
    "shot_assists": "Shot Assists",
    "losses_own_third": "# of Losses in Own Third",
    "losses_mid_third": "# of Losses in Middle Third",
    "match_tempo": "Match Tempo",
}

OVERALL_COLUMNS = [
    "number",
    "player_name",
    "minutes_played",
    "goals",
    "xg",
    "assists",
    "xa",
    "shots",
    "sot",
    "sot_rate",
    "total_passes",
    "total_passes_complete",
    "total_passing_accuracy",
    "crosses_attempted",
    "accurate_crosses",
    "crossing_accuracy",
    "dribbles_attempted",
    "successful_dribbles",
    "dribble_success_rate",
    "total_duels_attempted",
    "total_duels_won",
    "total_duel_win_rate",
    "losses",
    "losses_in_own_half",
    "recoveries",
    "recoveries_in_own_half",
    "touches_inside_box",
    "yellows",
    "reds",
]
